Correct MSVC build error after Bernard van der Helm's commit...
...of 24 May 2010 05:58:03.  hsccmd(179) error C2143: syntax error :
missing ';' before 'type'